# Generated by Django 4.0.1 on 2022-01-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scoping_topic_scoping_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoping',
            options={'ordering': ['-main', 'tag__name'], 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики Статьи'},
        ),
        migrations.RenameField(
            model_name='scoping',
            old_name='topic',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(through='articles.Scoping', to='articles.Topic'),
        ),
    ]
