# Generated by Django 4.0.1 on 2022-01-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_scoping_options_rename_topic_scoping_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='topic',
            new_name='scope',
        ),
    ]
